// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskWebsites.Data;

namespace TaskWebsites.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TaskWebsites.Models.HomepageSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FileType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Filename")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PathToFileOnDisk")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrlPath")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("HomepageSnapshot");
                });

            modelBuilder.Entity("TaskWebsites.Models.Website", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int?>("HomepageSnapshotId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("LoginId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("URL")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("HomepageSnapshotId");

                    b.HasIndex("LoginId");

                    b.ToTable("Websites");
                });

            modelBuilder.Entity("TaskWebsites.Models.WebsiteCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasAlternateKey("Name");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Automotive"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Banking"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Consumer"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Education"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Engineering"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Energy"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Fashion"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Financial"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Food and beverage"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Healthcare"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Insurance"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Legal"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Manufacturing"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Media"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Real estate"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Raw materials"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Religion"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Retail"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Jewelry"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Technology"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Telecommunications"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Government"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Transportation"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Non-profit"
                        });
                });

            modelBuilder.Entity("TaskWebsites.Models.WebsiteCredentials", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WebsiteCredentials");
                });

            modelBuilder.Entity("TaskWebsites.Models.Website", b =>
                {
                    b.HasOne("TaskWebsites.Models.WebsiteCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId");

                    b.HasOne("TaskWebsites.Models.HomepageSnapshot", "HomepageSnapshot")
                        .WithMany()
                        .HasForeignKey("HomepageSnapshotId");

                    b.HasOne("TaskWebsites.Models.WebsiteCredentials", "Login")
                        .WithMany()
                        .HasForeignKey("LoginId");
                });
#pragma warning restore 612, 618
        }
    }
}
